### ISSUE TITLE
jms-apache-activemq-sink-binding: error during trait customization: component not found for uri

### ISSUE THREAD

**Issue by bjethwan** [apache/camel-kamelets#1304]
IntegrationError
```
camel-k-integration-controller
Cannot reconcile Integration jms-apache-activemq-sink-binding: error during trait customization: component not found for uri "{{activemq-sink-local}}:{{destinationType}}:{{destinationName}}?conn
ectionFactory=%23bean%3A%7B%7BsinkConnectionFactoryBean-local%7D%7D" in camel catalog runtime version 1.16.0
```

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: jms-apache-activemq-sink-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: azure-servicebus-source
    properties:
      connectionString: Endpoint=sb://REMOVED.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=REMOVED
      topicOrQueueName: REMOVED
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: jms-apache-activemq-sink
    properties:
      brokerURL: tcp://active-mq.activemq.svc.cluster.local:61616
      destinationName: REMOVED
```

**Comment by sgdranesh** [comment]
I am also facing same issue

**Comment by oscerd** [comment]
This should be fixed in 1.12.0 on vote. Are you using 1.10?

**Comment by sgdranesh** [comment]
Warning  IntegrationError             22s   camel-k-integration-controller  Cannot reconcile Integration jms-apache-activemq-sink-bind
ing: error during trait customization: component not found for uri "{{activemq-sink-local}}:{{destinationType}}:{{destinationName}}?conn
ectionFactory=%23bean%3A%7B%7BsinkConnectionFactoryBean-local%7D%7D" in camel catalog runtime version 1.16.0

**Comment by oscerd** [comment]
ok, this just with Camel K.

**Comment by sgdranesh** [comment]
> This should be fixed in 1.12.0 on vote. Are you using 1.10?

Thank you for the reply.

I am using below helm repo to install camelK in kubernetes (AKS cluster)
**helm repo add camel-k https://apache.github.io/camel-k/charts**
I hope this will install latest version

**Comment by oscerd** [comment]
It's similar to: https://github.com/apache/camel-k/issues/4058

This is fixed in 1.12.0. We should release everything on Friday and next week there will be helm chart and operators.

**Comment by sgdranesh** [comment]
Thankyou.
Will wait for fix in next week.

**Comment by bjethwan** [comment]
@oscerd Dear Andrea,

I have a couple of stupid questions:
1. The version seen in the error "camel catalog runtime version 1.16.0" is higher than what you have quoted. Is the issue in the ActiceMQ Kamlet or the Camel-k Operator (not able to load the Kamlet)

2. Is there a workaround? Would the issue go away if we use a Java-based camel route?

**Comment by oscerd** [comment]
The version 1.16.0 is related to camel-k-runtime, which it's part of Camel K. The camel-k-runtime release 1.16.0 is part of Camel K 1.11.x, while 1.17.0 will be part of release 1.12.0.

If you need to use the stock Kamelet, there is no workaround if you choose KameletBinding. If you use java based Camel route you shouldn't have any problem.

**Comment by sgdranesh** [comment]
Hi Andrea,

Is camel-k-runtime-1.17.0 released?
Because Today I tried to update helm repo for camel-k and reinstalled camel-k
helm repo add camel-k https://apache.github.io/camel-k/charts

But still getting same error
  **Warning  IntegrationError             20m   camel-k-integration-controller  Cannot reconcile Integration jms-apache-activemq-sink-bind
ing: error during trait customization: component not found for uri "{{activemq-sink-local}}:{{destinationType}}:{{destinationName}}?conn
ectionFactory=%23bean%3A%7B%7BsinkConnectionFactoryBean-local%7D%7D" in camel catalog runtime version 1.16.0**


FYI.
We are installing this on Azure Kubernetes Services

**Comment by oscerd** [comment]
No it's not

**Comment by oscerd** [comment]
The release will be completed this week

**Comment by oscerd** [comment]
The helm chart for camel 1.12.0 is available.
